#!/bin/sh
. /etc/os-release

void="\e[0m"

if ps -aux | grep -q dwm; then
    wm="dwm"
elif ps -aux | grep -q bspwm; then
    wm="bspwm"
elif ps -aux | grep -q qtile; then
    wm="qtile"
elif ps -aux | grep -q xmonad; then
    wm="xmonad"
elif ps -aux | grep -q i3; then
    wm="i3"
elif ps -aux | grep -q openbox; then
    wm="openbox"
else
    wm="some wm"
fi

term="$TERM"
case $TERM in
    st-256color) term="st" ;;
esac
up="$(uptime -p)"

distro=$ID

line1="   __      "
line2="  |××|     "
line3=" ( \/ )    "
line4="  |--|     "
line5="  ^  ^     "

col1="\e[31m"
col2="\e[33m"

case "$distro" in
    "arch")
    line1="   /\      "
    line2="  _\ \     "
    line3=" /    \    "
    line4="/  ()  \   "
    line5=" -^  ^-    "

    col1="\e[31m"
    col2="\e[36m" ;;
    "debian")
    line1="  _--\     "
    line2=" / .  )    "
    line3=" (  -      "
    line4="  \        "
    line5="   ^       "

    col1="\e[34m"
    col2="\e[31m" ;;
    "fedora")
    line1="     --    "
    line2="    |  |   "
    line3="  - | -    "
    line4=" |  |      "
    line5="  --       "

    col1="\e[31m"
    col2="\e[34m" ;;
    "freebsd")
    line1=' /\----/\ '
    line2='/.`    `.\'
    line3='|        |'
    line4='|        |'
    line5=' `.____.` '

    col1="\e[33m"
    col2="\e[31m" ;;
    "gentoo")
    line1='  .`````.  '
    line2='.`   .   `.'
    line3='`..      .`'
    line4=' .`    .`  '
    line5='`.....`    '

    col1="\e[36m"
    col2="\e[35m" ;;
    "manjaro")
    line1="##### ##   "
    line2="## ## ##   "
    line3="## ## ##   "
    line4="## ## ##   "
    line5="## ## ##   "

    col1="\e[31m"
    col2="\e[32m" ;;
    "mint")
    line1="--------\  "
    line2="|   _ _  | "
    line3=" | / | \ | "
    line4=" | |   | | "
    line5=" \_______| "

    col1="\e[33m"
    col2="\e[32m" ;;
    "openbsd")
    line1="  -/\--    "
    line2="<  O  O  | "
    line3="|    3   > "
    line4=" <      /  "
    line5="    \/     "

    col1="\e[34m"
    col2="\e[33m" ;;
    "ubuntu")
    line1="    _-     "
    line2="  / __ \O  "
    line3="O( (  ) )  "
    line4="  \ -- /   "
    line5="    ~-O    "

    col1="\e[33m"
    col2="\e[31m" ;;
    "void")
    line1="     ###   "
    line2=" #      #  "
    line3=" #  ##  #  "
    line4=" #      #  "
    line5="  ###      "

    col1="\e[31m"
    col2="\e[32m" ;;
esac

fills(){
    n=$(echo "$line1" | wc -c)
	 for i in $(seq 1 $n); do printf " "; done
}

fills
echo -e "${col1}\e[1m${USER}@$(hostname)${void}"
echo -e "\e[1m${col2}${line1} os     ${void}${PRETTY_NAME}" 
echo -e "\e[1m${col2}${line2} kernel ${void}$(uname -r)"
echo -e "\e[1m${col2}${line3} uptime ${void}${up##up }"
echo -e "\e[1m${col2}${line4} shell  ${void}${SHELL##*/}"
echo -e "\e[1m${col2}${line5} wm     ${void}${wm}"
fills
echo -e "\e[1m${col2}term   ${void}${term}"
