#!/bin/sh
. /etc/os-release

void="\e[0m"

if grep -q dwm ~/.xinitrc; then
    wm="dwm"
elif grep -q bspwm ~/.xinitrc; then
    wm="bspwm"
elif grep -q qtile ~/.xinitrc; then
    wm="qtile"
elif grep -q xmonad ~/.xinitrc; then
    wm="xmonad"
elif grep -q i3 ~/.xinitrc; then
    wm="i3"
elif grep -q openbox ~/.xinitrc; then
    wm="openbox"
else
    wm="some wm"
fi

if [ ${NAME} = "Arch" ]; then
    line1="   /\    "
    line2="  _\ \   "
    line3=" /    \  "
    line4="/  ()  \ "
    line5=" -^  ^-  "

    col1="\e[31m"
    col2="\e[36m"
elif [ ${NAME} = "Debian" ]; then
    line1="  _--\   "
    line2=" / .  )  "
    line3=" (  -    "
    line4="  \      "
    line5="   ^     "

    col1="\e[34m"
    col2="\e[31m"
elif [ ${NAME} = "Fedora" ]; then
    line1="     ##  "
    line2="    #  # "
    line3="  #####  "
    line4=" #  #    "
    line5="  ##     "

    col1="\e[31m"
    col2="\e[34m"
elif [ ${NAME} = "FreeBSD" ]; then
    line1=' /\-----/\ '
    line2='/.`     `.\'
    line3='|         |'
    line4='|         |'
    line5=' `._____.` '

    col1="\e[33m"
    col2="\e[31m"
elif [ ${NAME} = "Gentoo" ]; then
    line1='  .`````.  '
	 line2='.`   .   `.'
	 line3='`-.      .`'
    line4=' .`    .`  '
    line5='`.....`    '

    col1="\e[36m"
    col2="\e[35m"
elif [ ${NAME} = "Manjaro" ]; then
    line1="##### ## "
    line2="## ## ## "
    line3="## ## ## "
    line4="## ## ## "
    line5="## ## ## "

    col1="\e[31m"
    col2="\e[32m"
elif [ ${NAME} = "Mint" ]; then
    line1="--------\ "
    line2="|   _ _  |"
    line3=" | / | \ |"
    line4=" | |   | |"
    line5=" \_______|"

    col1="\e[33m"
    col2="\e[32m"
elif [ ${NAME} = "OpenBSD" ]; then
    line1="  -/\--   "
    line2="<  O  O  |"
    line3="|    3   >"
    line4=" <      / "
    line5="    \/    "

    col1="\e[34m"
    col2="\e[33m"
elif [ ${NAME} = "Ubuntu" ]; then
    line1="    _-   "
    line2="  / __ \O"
    line3="O( (  ) )"
    line4="  \ -- / "
    line5="    ~-O  "

    col1="\e[33m"
    col2="\e[31m"
elif [ ${NAME} = "Void" ]; then
    line1="     ###  "
    line2=" #      # "
    line3=" #  ##  # "
    line4=" #      # "
    line5="  ###     "

    col1="\e[31m"
    col2="\e[32m"
else    
    line1="   __    "
    line2="  |××|   "
    line3=" ( \/ )  "
    line4="  |--|   "
    line5="  ^  ^   "

    col1="\e[31m"
    col2="\e[33m"
fi

echo -e "\e[1m${col2}${line1} ${col1}\e[1m${USER}@$(cat /proc/sys/kernel/hostname)${void}" 
echo -e "\e[1m${col2}${line2} ${col2}\e[1mos     ${void}${PRETTY_NAME}"
echo -e "\e[1m${col2}${line3} ${col2}\e[1mkernel ${void}$(cat /proc/sys/kernel/osrelease)"
echo -e "\e[1m${col2}${line4} ${col2}\e[1mshell  ${void}${SHELL##*/}"
echo -e "\e[1m${col2}${line5} ${col2}\e[1mwm     ${void}${wm}"
